server:
  port: 8081
spring:
  profiles:
    active: dev
---
server:
  port: 8083
spring:
  profiles: dev
---
server:
  port: 8084
spring:
  profiles: prod
---

person:
  name: zhangsan${random.uuid}
  age: ${random.int}
  boss: false
  birth: 2010/10/06
  maps: {k1: v1, k2: v2}
  lists:
    - lisi
    - zhaoliu
  dog:
    name: ${person.name}_xiaogou
    age: ${person.hello:5}

